//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MigrationTool.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binaries Verified.
        /// </summary>
        public static string BinariesVerified {
            get {
                return ResourceManager.GetString("BinariesVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Name.
        /// </summary>
        public static string BrowserName {
            get {
                return ResourceManager.GetString("BrowserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Solution.
        /// </summary>
        public static string BusinessSolution {
            get {
                return ResourceManager.GetString("BusinessSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Constraint.
        /// </summary>
        public static string CapacityConstraint {
            get {
                return ResourceManager.GetString("CapacityConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Rule.
        /// </summary>
        public static string CapacityRule {
            get {
                return ResourceManager.GetString("CapacityRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string CapacityRule_Average {
            get {
                return ResourceManager.GetString("CapacityRule_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcommit Ratio Antecedent.
        /// </summary>
        public static string CapacityRule_ComputeOvercommitAntecedent {
            get {
                return ResourceManager.GetString("CapacityRule_ComputeOvercommitAntecedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcommit Ratio Consequent.
        /// </summary>
        public static string CapacityRule_ComputeOvercommitConsequent {
            get {
                return ResourceManager.GetString("CapacityRule_ComputeOvercommitConsequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcommit Ratio.
        /// </summary>
        public static string CapacityRule_ComputeOvercommitRatio {
            get {
                return ResourceManager.GetString("CapacityRule_ComputeOvercommitRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute, {0} vCPU(s) per VM, {1:n0}:{2:n0} overcommit ratio.
        /// </summary>
        public static string CapacityRule_ComputeRuleDescription_P0_P1_P2 {
            get {
                return ResourceManager.GetString("CapacityRule_ComputeRuleDescription_P0_P1_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCPUs Per VM.
        /// </summary>
        public static string CapacityRule_ComputeVcpuCountType {
            get {
                return ResourceManager.GetString("CapacityRule_ComputeVcpuCountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCPUs Per VM.
        /// </summary>
        public static string CapacityRule_ComputeVcpusPerVm {
            get {
                return ResourceManager.GetString("CapacityRule_ComputeVcpusPerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Rules Inherited from Parent.
        /// </summary>
        public static string CapacityRule_Inherited {
            get {
                return ResourceManager.GetString("CapacityRule_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string CapacityRule_Maximum {
            get {
                return ResourceManager.GetString("CapacityRule_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0} VM(s) maximum per entity.
        /// </summary>
        public static string CapacityRule_MaximumRuleDescription_P0 {
            get {
                return ResourceManager.GetString("CapacityRule_MaximumRuleDescription_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum VMs.
        /// </summary>
        public static string CapacityRule_MaximumVms {
            get {
                return ResourceManager.GetString("CapacityRule_MaximumVms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Overhead Per Host.
        /// </summary>
        public static string CapacityRule_MemoryHostOverheadType {
            get {
                return ResourceManager.GetString("CapacityRule_MemoryHostOverheadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Per VM.
        /// </summary>
        public static string CapacityRule_MemoryPerVmType {
            get {
                return ResourceManager.GetString("CapacityRule_MemoryPerVmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory, {0} per VM.
        /// </summary>
        public static string CapacityRule_MemoryRuleDescription_MemoryPerVm_P0 {
            get {
                return ResourceManager.GetString("CapacityRule_MemoryRuleDescription_MemoryPerVm_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} overhead per host.
        /// </summary>
        public static string CapacityRule_MemoryRuleDescription_PerHostOverhead_P0 {
            get {
                return ResourceManager.GetString("CapacityRule_MemoryRuleDescription_PerHostOverhead_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} overhead per VM.
        /// </summary>
        public static string CapacityRule_MemoryRuleDescription_PerVmOverhead_P0 {
            get {
                return ResourceManager.GetString("CapacityRule_MemoryRuleDescription_PerVmOverhead_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Overhead Per VM.
        /// </summary>
        public static string CapacityRule_MemoryVmOverheadType {
            get {
                return ResourceManager.GetString("CapacityRule_MemoryVmOverheadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string CapacityRule_Minimum {
            get {
                return ResourceManager.GetString("CapacityRule_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CapacityRule_None {
            get {
                return ResourceManager.GetString("CapacityRule_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string CapacityRule_Percent {
            get {
                return ResourceManager.GetString("CapacityRule_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Type.
        /// </summary>
        public static string CapacityRule_RuleType {
            get {
                return ResourceManager.GetString("CapacityRule_RuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string CapacityRule_RuleType_Compute {
            get {
                return ResourceManager.GetString("CapacityRule_RuleType_Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum VMs Per Entity.
        /// </summary>
        public static string CapacityRule_RuleType_Maximum {
            get {
                return ResourceManager.GetString("CapacityRule_RuleType_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string CapacityRule_RuleType_Memory {
            get {
                return ResourceManager.GetString("CapacityRule_RuleType_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string CapacityRule_RuleType_Storage {
            get {
                return ResourceManager.GetString("CapacityRule_RuleType_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify.
        /// </summary>
        public static string CapacityRule_Specify {
            get {
                return ResourceManager.GetString("CapacityRule_Specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Overhead Per Data Store.
        /// </summary>
        public static string CapacityRule_StorageDataStoreOverheadType {
            get {
                return ResourceManager.GetString("CapacityRule_StorageDataStoreOverheadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} overhead per Data Store.
        /// </summary>
        public static string CapacityRule_StorageRuleDescription_PerDataStoreOverhead_P0 {
            get {
                return ResourceManager.GetString("CapacityRule_StorageRuleDescription_PerDataStoreOverhead_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} overhead per VM.
        /// </summary>
        public static string CapacityRule_StorageRuleDescription_PerVmOverhead_P0 {
            get {
                return ResourceManager.GetString("CapacityRule_StorageRuleDescription_PerVmOverhead_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage, {0} per VM.
        /// </summary>
        public static string CapacityRule_StorageRuleDescription_StoragePerVm_P0 {
            get {
                return ResourceManager.GetString("CapacityRule_StorageRuleDescription_StoragePerVm_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Overhead Per VM.
        /// </summary>
        public static string CapacityRule_StorageVmOverheadType {
            get {
                return ResourceManager.GetString("CapacityRule_StorageVmOverheadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Per VM.
        /// </summary>
        public static string CapacityRule_StorageVmSizeType {
            get {
                return ResourceManager.GetString("CapacityRule_StorageVmSizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string CapacityRule_Summary {
            get {
                return ResourceManager.GetString("CapacityRule_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Rules.
        /// </summary>
        public static string CapacityRulePlural {
            get {
                return ResourceManager.GetString("CapacityRulePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line.
        /// </summary>
        public static string CommandLine {
            get {
                return ResourceManager.GetString("CommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this {0}?.
        /// </summary>
        public static string ConfirmDeletion_P0 {
            get {
                return ResourceManager.GetString("ConfirmDeletion_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateAction {
            get {
                return ResourceManager.GetString("CreateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store.
        /// </summary>
        public static string DataStore {
            get {
                return ResourceManager.GetString("DataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store Category.
        /// </summary>
        public static string DataStoreCategory {
            get {
                return ResourceManager.GetString("DataStoreCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataStoreCategory_Id.
        /// </summary>
        public static string DataStoreCategory_Id {
            get {
                return ResourceManager.GetString("DataStoreCategory_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store Group.
        /// </summary>
        public static string DataStoreGroup {
            get {
                return ResourceManager.GetString("DataStoreGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataStoreGroup_Id.
        /// </summary>
        public static string DataStoreGroup_Id {
            get {
                return ResourceManager.GetString("DataStoreGroup_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Store Groups.
        /// </summary>
        public static string DataStoreGroupPlural {
            get {
                return ResourceManager.GetString("DataStoreGroupPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Stores.
        /// </summary>
        public static string DataStorePlural {
            get {
                return ResourceManager.GetString("DataStorePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailPlural {
            get {
                return ResourceManager.GetString("DetailPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsAction {
            get {
                return ResourceManager.GetString("DetailsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditAction {
            get {
                return ResourceManager.GetString("EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Life.
        /// </summary>
        public static string EndOfLife {
            get {
                return ResourceManager.GetString("EndOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        public static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Space.
        /// </summary>
        public static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Availability Calculation.
        /// </summary>
        public static string HighAvailabilityCalculation {
            get {
                return ResourceManager.GetString("HighAvailabilityCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor.
        /// </summary>
        public static string Hypervisor {
            get {
                return ResourceManager.GetString("Hypervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor Controller.
        /// </summary>
        public static string HypervisorController {
            get {
                return ResourceManager.GetString("HypervisorController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor Controllers.
        /// </summary>
        public static string HypervisorControllerPlural {
            get {
                return ResourceManager.GetString("HypervisorControllerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor Group.
        /// </summary>
        public static string HypervisorGroup {
            get {
                return ResourceManager.GetString("HypervisorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Builds.
        /// </summary>
        public static string HypervisorGroup_AcceptingNewBuilds {
            get {
                return ResourceManager.GetString("HypervisorGroup_AcceptingNewBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HypervisorGroup_Id.
        /// </summary>
        public static string HypervisorGroupId {
            get {
                return ResourceManager.GetString("HypervisorGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor Groups.
        /// </summary>
        public static string HypervisorGroupPlural {
            get {
                return ResourceManager.GetString("HypervisorGroupPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor Group Type.
        /// </summary>
        public static string HypervisorGroupType {
            get {
                return ResourceManager.GetString("HypervisorGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HypervisorGroupType_Id.
        /// </summary>
        public static string HypervisorGroupTypeId {
            get {
                return ResourceManager.GetString("HypervisorGroupTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisors.
        /// </summary>
        public static string HypervisorPlural {
            get {
                return ResourceManager.GetString("HypervisorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor Type.
        /// </summary>
        public static string HypervisorType {
            get {
                return ResourceManager.GetString("HypervisorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HypervisorType_Id.
        /// </summary>
        public static string HypervisorTypeId {
            get {
                return ResourceManager.GetString("HypervisorTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperVisor Version.
        /// </summary>
        public static string HyperVisorVersion {
            get {
                return ResourceManager.GetString("HyperVisorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypervisor Workload Profile.
        /// </summary>
        public static string HypervisorWorkloadProfile {
            get {
                return ResourceManager.GetString("HypervisorWorkloadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HypervisorWorkloadProfile_Id.
        /// </summary>
        public static string HypervisorWorkloadProfileId {
            get {
                return ResourceManager.GetString("HypervisorWorkloadProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average VCPUs per VM.
        /// </summary>
        public static string IComputeResource_AverageVcpusPerVm {
            get {
                return ResourceManager.GetString("IComputeResource_AverageVcpusPerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum VCPUs per VM.
        /// </summary>
        public static string IComputeResource_MaximumVcpusPerVm {
            get {
                return ResourceManager.GetString("IComputeResource_MaximumVcpusPerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum VCPUs per VM.
        /// </summary>
        public static string IComputeResource_MinimumVcpusPerVm {
            get {
                return ResourceManager.GetString("IComputeResource_MinimumVcpusPerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Memory per VM.
        /// </summary>
        public static string IMemoryResource_AverageMemoryPerVm {
            get {
                return ResourceManager.GetString("IMemoryResource_AverageMemoryPerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Memory per VM.
        /// </summary>
        public static string IMemoryResource_MaximumMemoryPerVm {
            get {
                return ResourceManager.GetString("IMemoryResource_MaximumMemoryPerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Memory per VM.
        /// </summary>
        public static string IMemoryResource_MinimumMemoryPerVm {
            get {
                return ResourceManager.GetString("IMemoryResource_MinimumMemoryPerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Date.
        /// </summary>
        public static string InactiveDate {
            get {
                return ResourceManager.GetString("InactiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes into account High Availability.
        /// </summary>
        public static string IncludesHighAvailability {
            get {
                return ResourceManager.GetString("IncludesHighAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string IndexAction {
            get {
                return ResourceManager.GetString("IndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of {0}.
        /// </summary>
        public static string IndexOf_P0 {
            get {
                return ResourceManager.GetString("IndexOf_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Storage Per VM.
        /// </summary>
        public static string IStorageResource_AverageStoragePerVm {
            get {
                return ResourceManager.GetString("IStorageResource_AverageStoragePerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Storage Per VM.
        /// </summary>
        public static string IStorageResource_MaximumStoragePerVm {
            get {
                return ResourceManager.GetString("IStorageResource_MaximumStoragePerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Storage Per VM.
        /// </summary>
        public static string IStorageResource_MinimumStoragePerVm {
            get {
                return ResourceManager.GetString("IStorageResource_MinimumStoragePerVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Storage.
        /// </summary>
        public static string LocalStorage {
            get {
                return ResourceManager.GetString("LocalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Core.
        /// </summary>
        public static string LogicalCore {
            get {
                return ResourceManager.GetString("LogicalCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Cores.
        /// </summary>
        public static string LogicalCorePlural {
            get {
                return ResourceManager.GetString("LogicalCorePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotePlural {
            get {
                return ResourceManager.GetString("NotePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcommit Ratio.
        /// </summary>
        public static string OvercommitRatio {
            get {
                return ResourceManager.GetString("OvercommitRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string PercentSignCharacter {
            get {
                return ResourceManager.GetString("PercentSignCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Cores.
        /// </summary>
        public static string ProcessorCorePlural {
            get {
                return ResourceManager.GetString("ProcessorCorePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Application.
        /// </summary>
        public static string PublishedApplication {
            get {
                return ResourceManager.GetString("PublishedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string RatioSeparatorCharacter {
            get {
                return ResourceManager.GetString("RatioSeparatorCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Hypervisors.
        /// </summary>
        public static string ReservedHypervisors {
            get {
                return ResourceManager.GetString("ReservedHypervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Percentage.
        /// </summary>
        public static string ReservedPercentage {
            get {
                return ResourceManager.GetString("ReservedPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Location.
        /// </summary>
        public static string SiteLocation {
            get {
                return ResourceManager.GetString("SiteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagPlural {
            get {
                return ResourceManager.GetString("TagPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Capacity.
        /// </summary>
        public static string TotalCapacity {
            get {
                return ResourceManager.GetString("TotalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Storage.
        /// </summary>
        public static string TotalStorage {
            get {
                return ResourceManager.GetString("TotalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Storage.
        /// </summary>
        public static string TotalStorageCapacity {
            get {
                return ResourceManager.GetString("TotalStorageCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Capacity.
        /// </summary>
        public static string UsedCapacity {
            get {
                return ResourceManager.GetString("UsedCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Capacity Percent.
        /// </summary>
        public static string UsedCapacityPercent {
            get {
                return ResourceManager.GetString("UsedCapacityPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Space.
        /// </summary>
        public static string UsedSpace {
            get {
                return ResourceManager.GetString("UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Storage.
        /// </summary>
        public static string UsedStorageCapacity {
            get {
                return ResourceManager.GetString("UsedStorageCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Storage Percent.
        /// </summary>
        public static string UsedStorageCapacityPercent {
            get {
                return ResourceManager.GetString("UsedStorageCapacityPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Hard Drives.
        /// </summary>
        public static string VirtualHardDrivePlural {
            get {
                return ResourceManager.GetString("VirtualHardDrivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM(s).
        /// </summary>
        public static string VirtualMachineOptionalPluralAbbreviated {
            get {
                return ResourceManager.GetString("VirtualMachineOptionalPluralAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machines.
        /// </summary>
        public static string VirtualMachinePlural {
            get {
                return ResourceManager.GetString("VirtualMachinePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCPU(s).
        /// </summary>
        public static string VirtualProcessorOptionalPluralAbbreviated {
            get {
                return ResourceManager.GetString("VirtualProcessorOptionalPluralAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Processors.
        /// </summary>
        public static string VirtualProcessorPlural {
            get {
                return ResourceManager.GetString("VirtualProcessorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine Capacity.
        /// </summary>
        public static string VmCapacity {
            get {
                return ResourceManager.GetString("VmCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity By Rule Type.
        /// </summary>
        public static string VmCapacity_ByRuleType {
            get {
                return ResourceManager.GetString("VmCapacity_ByRuleType", resourceCulture);
            }
        }
    }
}
